app = 'sfms-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ENV = 'production'
  DEBUG = 'false'
  PORT = '8001'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/api/v1/health"
  timeout = "5s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
